---
version: "3"
services:

  mvn:
    build: Build
    volumes:
      - type: volume
        source: app
        target: /home/git/target/WebApp.war

  web:
    build: Deploy
    volumes:
      - type: volume
        source: app
        target: /opt/tomcat/webapps/
    ports:
      - "8081:8080"
    depends_on:
      - mvn
volumes:
  app: